<script>
if(document.querySelector('.gallery__folder')!==null){
document.querySelectorAll('.gallery__folder').forEach((galleryfolder)=>{
galleryfolder.innerHTML =  " <?php galleryFolderFunction();?> "});
document.querySelectorAll('.gallery_folder_link').forEach((galleryLink)=>{
galleryLink.setAttribute('href', '<?php get_site_url();?>' + galleryLink.getAttribute('href'));
});

document.querySelectorAll('.gallery_folder--item').forEach((galleryItem)=>{
galleryItem.setAttribute('src', '<?php get_site_url();?>' + galleryItem.getAttribute('src'));
});
const galleryFolderSlideshow=document.createElement("div");galleryFolderSlideshow.classList.add("gallery_folder_slideshow");const galleryFolderSlideshowImg=document.createElement("img");galleryFolderSlideshow.appendChild(galleryFolderSlideshowImg),galleryFolderSlideshowImg.classList.add("gallery_folder_slideshow_img"),galleryFolderSlideshowImg.setAttribute("src","none"),document.body.appendChild(galleryFolderSlideshow),galleryFolderSlideshow.style.display="none";const galleryFolderSlideshowClose=document.createElement("div");galleryFolderSlideshowClose.classList.add("gallery_folder_slideshow_close"),galleryFolderSlideshowClose.innerHTML="<div class='close icon'></div>",galleryFolderSlideshow.appendChild(galleryFolderSlideshowClose),document.querySelectorAll(".gallery_folder_link").forEach(l=>{l.addEventListener("click",e=>{e.preventDefault(),console.log(l.getAttribute("href")),galleryFolderSlideshow.style.display="flex",galleryFolderSlideshowImg.setAttribute("src",l.getAttribute("href"))})}),galleryFolderSlideshowClose.addEventListener("click",()=>{galleryFolderSlideshow.style.display="none"});const galleryFolderSlideshowNext=document.createElement("button");galleryFolderSlideshowNext.classList.add("gallery_folder_slideshow_next"),galleryFolderSlideshow.appendChild(galleryFolderSlideshowNext);const galleryFolderSlideshowPrev=document.createElement("button");galleryFolderSlideshowPrev.classList.add("gallery_folder_slideshow_prev"),galleryFolderSlideshowPrev.innerHTML="<div class='arrow-left icon'></div> ",galleryFolderSlideshowNext.innerHTML="<div class='arrow-right icon'></div> ",galleryFolderSlideshow.appendChild(galleryFolderSlideshowPrev);let galleryCount=1;galleryFolderSlideshowNext.addEventListener("click",()=>{galleryFolderSlideshowImg.setAttribute("src",document.querySelectorAll(".gallery_folder_link")[galleryCount].getAttribute("href")),galleryCount++,console.log(galleryCount),galleryCount>=document.querySelectorAll(".gallery_folder_link").length&&(galleryCount=0)}),galleryFolderSlideshowPrev.addEventListener("click",()=>{galleryFolderSlideshowImg.setAttribute("src",document.querySelectorAll(".gallery_folder_link")[galleryCount].getAttribute("href")),galleryCount--,console.log(galleryCount),galleryCount<=-1&&(galleryCount=document.querySelectorAll(".gallery_folder_link").length),galleryCount==document.querySelectorAll(".gallery_folder_link").length&&(galleryCount=0)});
};
</script>